fixtures:
  repositories:
    'stdlib':
      repo: 'https://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '4.6.0'
    'firewall':
      repo: 'https://github.com/puppetlabs/puppetlabs-firewall.git'
      ref: '1.7.1'
  symlinks:
    'monit': "#{source_dir}"
